### ISSUE TITLE
Fees seem quirky

### ISSUE THREAD

**Issue by Folas1337** [MRollin03/JobActions#7]
Using `/order create stone 10 100` with the following config:
```yaml
Order:
  order-basefee: 10 # The fee the person creates a new order. This is mainly to prevent using orders as a teleportation system.
  order-base-fee-activated: true #If this is set to true, the base-fee is added to the payment amount.
  order-fee-percentage: 10 # The extra fee in percentage, that is added on top of  the base fee
  order-fee-percentage-activated: true #If this is set to true, the fee is a percentage of the initial price rather than a fixed amount of money
```
Results in:
- The person creating the order pays 100 coins
- The price on `/market` is 90 coins
- The person completing it receives 90 coins

But according to the comments in the config the item should have gone up for 80 coins as it first charges 10 for the base fee and another 10% for the percentage fee, both resulting in a subtraction of 10 coins from the original price.

----

Even more confusing, the following config:
```yaml
Order:
  order-basefee: 10 # The fee the person creates a new order. This is mainly to prevent using orders as a teleportation system.
  order-base-fee-activated: false #If this is set to true, the base-fee is added to the payment amount.
  order-fee-percentage: 10 # The extra fee in percentage, that is added on top of  the base fee
  order-fee-percentage-activated: true #If this is set to true, the fee is a percentage of the initial price rather than a fixed amount of money
```
Results in:
- The person creating the order pays 100 coins
- The price on `/market` is 10 coins
- The person completing it receives 10 coins

But it should have resulted in 90 coins on `/market` and not 10 because the fee should have been 10% which means 10 coins which should have been subtracted from the 100.

----

Lastly the following config:
```yaml
Order:
  order-basefee: 10 # The fee the person creates a new order. This is mainly to prevent using orders as a teleportation system.
  order-base-fee-activated: true #If this is set to true, the base-fee is added to the payment amount.
  order-fee-percentage: 10 # The extra fee in percentage, that is added on top of  the base fee
  order-fee-percentage-activated: false #If this is set to true, the fee is a percentage of the initial price rather than a fixed amount of money
```
Results in:
- The person creating the order pays 100 coins
- The price on `/market` is 90 coins
- The person completing it receives 90 coins

Which means that this is the only properly working setup
